### ISSUE TITLE
Php_Cahier_des_charges_non_respecté

### ISSUE THREAD

**Issue by wezerg** [DamienSasso/EFFicom-BTS-SIO-2-Eme-Annee#1]
Bonjour, le cahier des charges n'étant pas respecté a la date du 11/09/19 je vous retransmet le nouveaux cahier des charges. Il faudra adapter votre code avec la mention en gras :

-Vous créer une tableau de 30 cases, vous placer un nombre entre 0 et 100 dans chaque case. Parcourir le tableau et afficher le nombre de fois ou chaque valeur est affiché dans le tableau;
On doit afficher a la fin : La valeur xx est présente xx fois dans le tableau 
**SI LA VALEUR EST PRESENTE PLUS D'UNE FOIS, AFFICHER LE RESULTAT EN ROUGE**

**Comment by DamienSasso** [comment]
Merci pour cette remarque, cela sera corriger dans les plus bref délais,
cordialement.
